apiVersion: v1
kind: Service
metadata:
  name: github.com/clubhub/sales-service
spec:
  selector:
    app: github.com/clubhub/sales
  ports:
    - protocol: TCP
      port: 8089        
      targetPort: 8089  
  type: LoadBalancer 